/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IBase64, IBase64Interface } from "../IBase64";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "encode",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class IBase64__factory {
  static readonly abi = _abi;
  static createInterface(): IBase64Interface {
    return new utils.Interface(_abi) as IBase64Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBase64 {
    return new Contract(address, _abi, signerOrProvider) as IBase64;
  }
}
