"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IExquisiteGraphics__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
  {
    inputs: [],
    name: "BackgroundColorIndexOutOfRange",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxColors",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxColumns",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxPixels",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxRows",
    type: "error",
  },
  {
    inputs: [],
    name: "MissingHeader",
    type: "error",
  },
  {
    inputs: [],
    name: "NotEnoughData",
    type: "error",
  },
  {
    inputs: [],
    name: "PixelColorIndexOutOfRange",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "decodeDrawContext",
    outputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
          {
            components: [
              {
                internalType: "uint8",
                name: "version",
                type: "uint8",
              },
              {
                internalType: "uint16",
                name: "width",
                type: "uint16",
              },
              {
                internalType: "uint16",
                name: "height",
                type: "uint16",
              },
              {
                internalType: "uint16",
                name: "numColors",
                type: "uint16",
              },
              {
                internalType: "uint8",
                name: "backgroundColorIndex",
                type: "uint8",
              },
              {
                internalType: "uint16",
                name: "scale",
                type: "uint16",
              },
              {
                internalType: "uint8",
                name: "reserved",
                type: "uint8",
              },
              {
                internalType: "bool",
                name: "alpha",
                type: "bool",
              },
              {
                internalType: "bool",
                name: "hasBackground",
                type: "bool",
              },
              {
                internalType: "uint24",
                name: "totalPixels",
                type: "uint24",
              },
              {
                internalType: "uint8",
                name: "bitsPerPixel",
                type: "uint8",
              },
              {
                internalType: "uint8",
                name: "pixelsPerByte",
                type: "uint8",
              },
              {
                internalType: "uint16",
                name: "paletteStart",
                type: "uint16",
              },
              {
                internalType: "uint16",
                name: "dataStart",
                type: "uint16",
              },
            ],
            internalType: "struct IExquisiteGraphics.Header",
            name: "header",
            type: "tuple",
          },
          {
            internalType: "string[]",
            name: "palette",
            type: "string[]",
          },
          {
            internalType: "uint8[]",
            name: "pixels",
            type: "uint8[]",
          },
        ],
        internalType: "struct IExquisiteGraphics.DrawContext",
        name: "ctx",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "decodeHeader",
    outputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "version",
            type: "uint8",
          },
          {
            internalType: "uint16",
            name: "width",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "height",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "numColors",
            type: "uint16",
          },
          {
            internalType: "uint8",
            name: "backgroundColorIndex",
            type: "uint8",
          },
          {
            internalType: "uint16",
            name: "scale",
            type: "uint16",
          },
          {
            internalType: "uint8",
            name: "reserved",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "alpha",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "hasBackground",
            type: "bool",
          },
          {
            internalType: "uint24",
            name: "totalPixels",
            type: "uint24",
          },
          {
            internalType: "uint8",
            name: "bitsPerPixel",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "pixelsPerByte",
            type: "uint8",
          },
          {
            internalType: "uint16",
            name: "paletteStart",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "dataStart",
            type: "uint16",
          },
        ],
        internalType: "struct IExquisiteGraphics.Header",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "decodePalette",
    outputs: [
      {
        internalType: "string[]",
        name: "",
        type: "string[]",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "draw",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "drawPixels",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "drawPixelsUnsafe",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "drawUnsafe",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "ty",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "ty",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "validate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "validateHeader",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];
class IExquisiteGraphics__factory {
  static createInterface() {
    return new ethers_1.utils.Interface(_abi);
  }
  static connect(address, signerOrProvider) {
    return new ethers_1.Contract(address, _abi, signerOrProvider);
  }
}
exports.IExquisiteGraphics__factory = IExquisiteGraphics__factory;
IExquisiteGraphics__factory.abi = _abi;
