/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IExquisiteGraphics,
  IExquisiteGraphicsInterface,
} from "../IExquisiteGraphics";

const _abi = [
  {
    inputs: [],
    name: "BackgroundColorIndexOutOfRange",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxColors",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxColumns",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxPixels",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxRows",
    type: "error",
  },
  {
    inputs: [],
    name: "MissingHeader",
    type: "error",
  },
  {
    inputs: [],
    name: "NotEnoughData",
    type: "error",
  },
  {
    inputs: [],
    name: "PixelColorIndexOutOfRange",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "decodeDrawContext",
    outputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
          {
            components: [
              {
                internalType: "uint8",
                name: "version",
                type: "uint8",
              },
              {
                internalType: "uint16",
                name: "width",
                type: "uint16",
              },
              {
                internalType: "uint16",
                name: "height",
                type: "uint16",
              },
              {
                internalType: "uint16",
                name: "numColors",
                type: "uint16",
              },
              {
                internalType: "uint8",
                name: "backgroundColorIndex",
                type: "uint8",
              },
              {
                internalType: "uint16",
                name: "scale",
                type: "uint16",
              },
              {
                internalType: "uint8",
                name: "reserved",
                type: "uint8",
              },
              {
                internalType: "bool",
                name: "alpha",
                type: "bool",
              },
              {
                internalType: "bool",
                name: "hasBackground",
                type: "bool",
              },
              {
                internalType: "uint24",
                name: "totalPixels",
                type: "uint24",
              },
              {
                internalType: "uint8",
                name: "bitsPerPixel",
                type: "uint8",
              },
              {
                internalType: "uint8",
                name: "pixelsPerByte",
                type: "uint8",
              },
              {
                internalType: "uint16",
                name: "paletteStart",
                type: "uint16",
              },
              {
                internalType: "uint16",
                name: "dataStart",
                type: "uint16",
              },
            ],
            internalType: "struct IExquisiteGraphics.Header",
            name: "header",
            type: "tuple",
          },
          {
            internalType: "string[]",
            name: "palette",
            type: "string[]",
          },
          {
            internalType: "uint8[]",
            name: "pixels",
            type: "uint8[]",
          },
        ],
        internalType: "struct IExquisiteGraphics.DrawContext",
        name: "ctx",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "decodeHeader",
    outputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "version",
            type: "uint8",
          },
          {
            internalType: "uint16",
            name: "width",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "height",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "numColors",
            type: "uint16",
          },
          {
            internalType: "uint8",
            name: "backgroundColorIndex",
            type: "uint8",
          },
          {
            internalType: "uint16",
            name: "scale",
            type: "uint16",
          },
          {
            internalType: "uint8",
            name: "reserved",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "alpha",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "hasBackground",
            type: "bool",
          },
          {
            internalType: "uint24",
            name: "totalPixels",
            type: "uint24",
          },
          {
            internalType: "uint8",
            name: "bitsPerPixel",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "pixelsPerByte",
            type: "uint8",
          },
          {
            internalType: "uint16",
            name: "paletteStart",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "dataStart",
            type: "uint16",
          },
        ],
        internalType: "struct IExquisiteGraphics.Header",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "decodePalette",
    outputs: [
      {
        internalType: "string[]",
        name: "",
        type: "string[]",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "draw",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "drawPixels",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "drawPixelsUnsafe",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "drawUnsafe",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "ty",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "ty",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "validate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "validateHeader",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

export class IExquisiteGraphics__factory {
  static readonly abi = _abi;
  static createInterface(): IExquisiteGraphicsInterface {
    return new utils.Interface(_abi) as IExquisiteGraphicsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExquisiteGraphics {
    return new Contract(address, _abi, signerOrProvider) as IExquisiteGraphics;
  }
}
